// src/components/courses/CourseViewer.jsx
// Read-only viewer for courses — no editing, no drag-and-drop
import { useState } from 'react';
import { ArrowLeft, PencilLine, Download } from 'lucide-react';

const CourseViewer = ({
  courseName,
  sections,
  handsOnResources,
  ownerName,
  isOwner,
  isCollaborator,
  onEditInWorkspace,
  onEditAsCollaborator,
  navigate
}) => {
  const [collapsedSections, setCollapsedSections] = useState({});
  const [collapsedSubsections, setCollapsedSubsections] = useState({});

  const toggleSection = (id) => setCollapsedSections(prev => ({ ...prev, [id]: !prev[id] }));
  const toggleSubsection = (id) => setCollapsedSubsections(prev => ({ ...prev, [id]: !prev[id] }));

  const handleDownloadTxt = () => {
    const lines = [];
    lines.push(`COURSE: ${courseName}`);
    lines.push('Generated by EdCube');
    lines.push('');

    sections.forEach((section, sIdx) => {
      if (section.type === 'break') {
        lines.push(`--- BREAK: ${section.duration} ---`);
        lines.push('');
        return;
      }

      lines.push('='.repeat(60));
      lines.push(`SECTION ${sIdx + 1}: ${section.title}`);
      if (section.description) lines.push(section.description);
      lines.push('');

      (section.subsections || []).forEach((sub, subIdx) => {
        lines.push(`  ${sIdx + 1}.${subIdx + 1} ${sub.title}`);
        if (sub.description) lines.push(`  ${sub.description}`);
        if (sub.duration_minutes) lines.push(`  Duration: ${sub.duration_minutes} min`);
        if ((sub.learning_objectives || []).length > 0) {
          lines.push('  Learning Objectives:');
          sub.learning_objectives.forEach(obj => lines.push(`    - ${obj}`));
        }

        const blocks = handsOnResources[sub.id] || [];
        const contentBlocks = blocks.filter(b => b.type === 'content');
        const worksheets = blocks.filter(b => b.type === 'worksheet');
        const activities = blocks.filter(b => b.type === 'activity');

        if (contentBlocks.length > 0) {
          lines.push('  Content:');
          contentBlocks.forEach(b => lines.push(`    - ${b.title}${b.url ? ': ' + b.url : ''}`));
        }
        if (worksheets.length > 0) {
          lines.push('  Worksheets:');
          worksheets.forEach(b => lines.push(`    - ${b.title}${b.url ? ': ' + b.url : ''}`));
        }
        if (activities.length > 0) {
          lines.push('  Activities:');
          activities.forEach(b => lines.push(`    - ${b.title}${b.url ? ': ' + b.url : ''}`));
        }
        lines.push('');
      });
    });

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${courseName.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // ── Block type config ────────────────────────────────────────────────
  const blockConfig = {
    content:   { label: 'Content',   bg: '#EAF0FF', color: '#6B8FE8' },
    worksheet: { label: 'Worksheet', bg: '#FFF3E8', color: '#E8A55C' },
    activity:  { label: 'Activity',  bg: '#EDFFF3', color: '#5CC97C' },
  };

  // ── Colors — matches CourseEditor exactly ─────────────────────────────
  const colors = {
    bg: '#F7F5F0',
    card: '#FFFFFF',
    sectionBorder: '#E7E5E4',
    sectionBg: '#FFFFFF',
    sectionStripe: '#52A67A',
    subsectionBg: '#FFFFFF',
    subsectionBorder: '#E7E5E4',
    subsectionStripe: '#5B8FBD',
    textPrimary: '#111',
    textSecondary: '#111',
    pillBg: '#F5F5F4',
    pillText: '#333',
  };

  // ── Section (read-only) ──────────────────────────────────────────────
  const SectionView = ({ section, index }) => {
    if (section.type === 'break') {
      return (
        <div style={{
          padding: '12px 16px', marginBottom: '16px',
          backgroundColor: '#FFF9E6', border: `1px solid ${colors.sectionBorder}`,
          borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '8px'
        }}>
          <span style={{ fontWeight: '500', fontSize: '15.4px', color: colors.textPrimary }}>
            ⏸️ Break — {section.duration}
          </span>
        </div>
      );
    }

    const isCollapsed = collapsedSections[section.id];

    return (
      <div style={{
        border: `1px solid ${colors.sectionBorder}`,
        borderRadius: '12px',
        marginBottom: '16px',
        backgroundColor: colors.card,
        overflow: 'hidden',
        boxShadow: '0 1px 3px rgba(0,0,0,0.06)'
      }}>
        {/* Section header */}
        <div style={{
          backgroundColor: colors.sectionBg,
          display: 'flex',
          alignItems: 'center',
          borderBottom: isCollapsed ? 'none' : `1px solid ${colors.sectionBorder}`
        }}>
          <div style={{
            width: '5px',
            alignSelf: 'stretch',
            backgroundColor: colors.sectionStripe,
            flexShrink: 0
          }} />

          <div style={{ flex: 1, padding: '12px 14px', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <button
              onClick={() => toggleSection(section.id)}
              style={{
                background: 'none', border: 'none', cursor: 'pointer',
                fontSize: '12.1px', color: colors.sectionStripe, padding: 0, flexShrink: 0,
                transition: 'transform 0.2s',
                transform: isCollapsed ? 'rotate(0deg)' : 'rotate(90deg)'
              }}
            >
              ▶
            </button>

            <span style={{
              fontSize: '11px', fontWeight: '700', textTransform: 'uppercase',
              letterSpacing: '0.7px', color: colors.sectionStripe,
              background: '#DCFCE7', padding: '2px 7px', borderRadius: '4px', flexShrink: 0
            }}>
              Section {index + 1}
            </span>

            <span style={{
              fontSize: '18px', fontWeight: '600', color: '#111',
              flex: 1, letterSpacing: '-0.2px'
            }}>
              {section.title}
            </span>
          </div>
        </div>

        {/* Section description */}
        {!isCollapsed && section.description && (
          <div style={{
            backgroundColor: '#FAFAF9',
            padding: '9px 16px 9px 21px',
            borderBottom: `1px solid ${colors.sectionBorder}`
          }}>
            <span style={{ fontSize: '14px', color: '#333', display: 'block', wordBreak: 'break-word', whiteSpace: 'pre-wrap' }}>
              {section.description}
            </span>
          </div>
        )}

        {/* Subsections */}
        {!isCollapsed && (
          <div style={{ padding: '14px 16px' }}>
            {(section.subsections || []).length === 0 ? (
              <div style={{
                textAlign: 'center', padding: '24px 20px',
                border: '1px dashed #e5e7eb', borderRadius: '8px',
                backgroundColor: '#fafafa', color: '#444', fontSize: '14px'
              }}>
                No subsections in this section
              </div>
            ) : (
              (section.subsections || []).map((sub, subIdx) => {
                const isSubCollapsed = collapsedSubsections[sub.id];
                const blocks = handsOnResources[sub.id] || [];

                return (
                  <div key={sub.id} style={{ marginBottom: '10px' }}>
                    <div style={{
                      border: `1px solid ${colors.subsectionBorder}`,
                      borderRadius: '10px',
                      backgroundColor: colors.subsectionBg,
                      overflow: 'hidden'
                    }}>
                      {/* Subsection header */}
                      <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        borderBottom: isSubCollapsed ? 'none' : `1px solid ${colors.subsectionBorder}`
                      }}>
                        <div style={{
                          width: '4px', alignSelf: 'stretch',
                          backgroundColor: colors.subsectionStripe, flexShrink: 0
                        }} />

                        <div
                          style={{ flex: 1, padding: '9px 12px', display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}
                          onClick={() => toggleSubsection(sub.id)}
                        >
                          <button style={{
                            background: 'none', border: 'none', cursor: 'pointer',
                            fontSize: '11px', color: colors.subsectionStripe, padding: 0, flexShrink: 0,
                            transition: 'transform 0.2s',
                            transform: isSubCollapsed ? 'rotate(0deg)' : 'rotate(90deg)'
                          }}>
                            ▶
                          </button>

                          <span style={{
                            fontSize: '11px', fontWeight: '700', textTransform: 'uppercase',
                            letterSpacing: '0.6px', color: colors.subsectionStripe, flexShrink: 0
                          }}>
                            {index + 1}.{subIdx + 1}
                          </span>

                          <span style={{
                            fontSize: '15px', fontWeight: '600', color: '#111', flex: 1
                          }}>
                            {sub.title}
                          </span>

                          {sub.duration_minutes > 0 && (
                            <span style={{
                              fontSize: '12px', color: '#666', flexShrink: 0,
                              backgroundColor: colors.pillBg, padding: '2px 8px', borderRadius: '4px'
                            }}>
                              🕐 {sub.duration_minutes} min
                            </span>
                          )}

                          <span style={{
                            fontSize: '12px', color: '#888', flexShrink: 0
                          }}>
                            {blocks.length} block{blocks.length !== 1 ? 's' : ''}
                          </span>
                        </div>
                      </div>

                      {!isSubCollapsed && (
                        <div style={{ padding: '12px 14px' }}>
                          {/* Subsection description */}
                          {sub.description && (
                            <p style={{
                              margin: '0 0 10px', fontSize: '14px', color: '#333',
                              wordBreak: 'break-word', whiteSpace: 'pre-wrap', lineHeight: '1.5'
                            }}>
                              {sub.description}
                            </p>
                          )}

                          {/* Learning objectives */}
                          {(sub.learning_objectives || []).length > 0 && (
                            <div style={{ marginBottom: '12px' }}>
                              <p style={{ margin: '0 0 6px', fontSize: '12px', fontWeight: '700', color: '#555', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
                                Learning Objectives
                              </p>
                              <ul style={{ margin: 0, paddingLeft: '18px', fontSize: '13.5px', color: '#333', lineHeight: '1.6' }}>
                                {sub.learning_objectives.map((obj, i) => (
                                  <li key={i}>{obj}</li>
                                ))}
                              </ul>
                            </div>
                          )}

                          {/* Blocks grid */}
                          {blocks.length === 0 ? (
                            <div style={{
                              textAlign: 'center', padding: '20px',
                              border: '1px dashed #e5e7eb', borderRadius: '8px',
                              backgroundColor: '#fafafa', color: '#888', fontSize: '13px'
                            }}>
                              No blocks in this subsection
                            </div>
                          ) : (
                            <div style={{
                              display: 'grid',
                              gridTemplateColumns: 'repeat(auto-fill, minmax(150px, 1fr))',
                              gap: '10px'
                            }}>
                              {blocks.map(block => {
                                const cfg = blockConfig[block.type] || blockConfig.content;
                                const BlockWrapper = block.url ? 'a' : 'div';
                                const linkProps = block.url
                                  ? { href: block.url, target: '_blank', rel: 'noopener noreferrer', onClick: e => e.stopPropagation() }
                                  : {};
                                return (
                                  <BlockWrapper
                                    key={block.id}
                                    {...linkProps}
                                    style={{
                                      aspectRatio: '1/1',
                                      backgroundColor: cfg.bg,
                                      border: `1.5px solid ${cfg.color}33`,
                                      borderRadius: '10px',
                                      padding: '12px',
                                      display: 'flex',
                                      flexDirection: 'column',
                                      justifyContent: 'space-between',
                                      cursor: block.url ? 'pointer' : 'default',
                                      textDecoration: 'none',
                                      boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
                                      transition: 'box-shadow 0.15s, transform 0.15s'
                                    }}
                                    onMouseEnter={e => {
                                      e.currentTarget.style.boxShadow = '0 4px 10px rgba(0,0,0,0.1)';
                                      e.currentTarget.style.transform = 'translateY(-1px)';
                                    }}
                                    onMouseLeave={e => {
                                      e.currentTarget.style.boxShadow = '0 1px 3px rgba(0,0,0,0.05)';
                                      e.currentTarget.style.transform = 'translateY(0)';
                                    }}
                                  >
                                    <div>
                                      <span style={{
                                        fontSize: '10.5px', fontWeight: '700', textTransform: 'uppercase',
                                        letterSpacing: '0.5px', color: cfg.color,
                                        backgroundColor: `${cfg.color}22`,
                                        padding: '2px 6px', borderRadius: '4px',
                                        display: 'inline-block', marginBottom: '8px'
                                      }}>
                                        {cfg.label}
                                      </span>
                                      <p style={{
                                        margin: 0, fontSize: '13px', fontWeight: '600',
                                        color: '#111', lineHeight: '1.35',
                                        overflow: 'hidden',
                                        display: '-webkit-box',
                                        WebkitLineClamp: 3,
                                        WebkitBoxOrient: 'vertical'
                                      }}>
                                        {block.title}
                                      </p>
                                    </div>
                                    {block.url && (
                                      <span style={{ fontSize: '11px', color: cfg.color, fontWeight: '600' }}>
                                        Open →
                                      </span>
                                    )}
                                  </BlockWrapper>
                                );
                              })}
                            </div>
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })
            )}
          </div>
        )}
      </div>
    );
  };

  // ── Stats ────────────────────────────────────────────────────────────
  const sectionCount = sections.filter(s => s.type !== 'break').length;
  const subsectionCount = sections.reduce((acc, s) => acc + (s.subsections?.length || 0), 0);
  const blockCount = Object.values(handsOnResources || {}).reduce((acc, arr) => acc + (arr?.length || 0), 0);

  // ── Render ───────────────────────────────────────────────────────────
  return (
    <>
      {/* Top Bar */}
      <div style={{
        padding: '12px 28px', borderBottom: `1px solid ${colors.sectionBorder}`,
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        backgroundColor: 'white', boxShadow: '0 1px 3px rgba(0,0,0,0.06)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>
          <h2 style={{ margin: 0, fontSize: '22px', color: colors.textPrimary }}>EdCube</h2>
          <span style={{ fontSize: '18.7px', fontWeight: '600', color: colors.textPrimary }}>
            {courseName}
          </span>
          <span style={{
            fontSize: '12.1px',
            color: isOwner ? '#1d4ed8' : '#059669',
            backgroundColor: isOwner ? '#EFF6FF' : '#ECFDF5',
            padding: '3px 8px', borderRadius: '10px', fontWeight: '600'
          }}>
            {isOwner ? 'View Mode' : 'View Only'}
          </span>
          {ownerName && (
            <span style={{
              fontSize: '13px', color: '#333', backgroundColor: '#f3f4f6',
              padding: '4px 10px', borderRadius: '12px', fontWeight: '500'
            }}>
              By {ownerName}
            </span>
          )}
        </div>

        <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
          {isOwner && (
            <button
              onClick={handleDownloadTxt}
              style={{
                display: 'flex', alignItems: 'center', gap: '6px',
                padding: '7px 14px',
                backgroundColor: '#fff',
                color: '#111',
                border: '1px solid #d1d5db', borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '14.3px', fontWeight: '500',
                transition: 'background-color 0.15s ease'
              }}
              onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = '#f9fafb'; }}
              onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = '#fff'; }}
              title="Download course as TXT"
            >
              <Download size={14} />
              Download
            </button>
          )}
          {isOwner && onEditInWorkspace && (
            <button
              onClick={onEditInWorkspace}
              style={{
                display: 'flex', alignItems: 'center', gap: '6px',
                padding: '7px 16px',
                backgroundColor: '#1d4ed8',
                color: 'white',
                border: 'none', borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '14.3px', fontWeight: '600',
                transition: 'background-color 0.15s ease'
              }}
              onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = '#1e40af'; }}
              onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = '#1d4ed8'; }}
            >
              <PencilLine size={14} />
              Edit in Course Workspace
            </button>
          )}
          {isCollaborator && onEditAsCollaborator && (
            <button
              onClick={onEditAsCollaborator}
              style={{
                display: 'flex', alignItems: 'center', gap: '6px',
                padding: '7px 16px',
                backgroundColor: '#059669',
                color: 'white',
                border: 'none', borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '14.3px', fontWeight: '600',
                transition: 'background-color 0.15s ease'
              }}
              onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = '#047857'; }}
              onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = '#059669'; }}
            >
              <PencilLine size={14} />
              Edit as Collaborator
            </button>
          )}
          <button
            onClick={() => navigate(-1)}
            style={{
              display: 'flex', alignItems: 'center', gap: '6px',
              padding: '7px 14px', backgroundColor: '#6b7280', color: 'white',
              border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '14.3px'
            }}
          >
            <ArrowLeft size={14} /> Back
          </button>
        </div>
      </div>

      {/* Stats bar */}
      <div style={{
        padding: '10px 28px', backgroundColor: 'white',
        borderBottom: `1px solid ${colors.sectionBorder}`,
        display: 'flex', gap: '10px', alignItems: 'center', justifyContent: 'center'
      }}>
        <span style={{ fontSize: '14px', color: '#444' }}>
          {sectionCount} section{sectionCount !== 1 ? 's' : ''} {'\u2022'}{' '}
          {subsectionCount} subsection{subsectionCount !== 1 ? 's' : ''} {'\u2022'}{' '}
          {blockCount} block{blockCount !== 1 ? 's' : ''}
        </span>
      </div>

      {/* Main content */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '24px 28px', backgroundColor: colors.bg }}>
        {sections.length === 0 ? (
          <div style={{
            textAlign: 'center', padding: '80px 20px',
            border: `1px solid ${colors.sectionBorder}`, borderRadius: '16px',
            backgroundColor: 'white'
          }}>
            <p style={{ fontSize: '17.6px', color: colors.textPrimary, fontWeight: '600', margin: '0 0 4px' }}>
              This course has no sections yet
            </p>
          </div>
        ) : (
          sections.map((section, idx) => (
            <SectionView key={section.id} section={section} index={idx} />
          ))
        )}
      </div>
    </>
  );
};

export default CourseViewer;
