// src/components/courses/CourseViewer.jsx
// Read-only viewer for courses — no editing, no drag-and-drop
import { useState } from 'react';
import { ArrowLeft, Edit2, PlayCircle, FileText, Zap, PencilLine, Download } from 'lucide-react';
import TopicDetailsModal from '../modals/TopicDetailsModal';

const CourseViewer = ({
  courseName,
  sections,
  videosByTopic,
  handsOnResources,
  ownerName,
  isOwner,
  isCollaborator,
  onEditInWorkspace,
  onEditAsCollaborator,
  navigate
}) => {
  const [selectedTopic, setSelectedTopic] = useState(null);
  const [collapsedSections, setCollapsedSections] = useState({});
  const [collapsedSubsections, setCollapsedSubsections] = useState({});

  const toggleSection = (id) => setCollapsedSections(prev => ({ ...prev, [id]: !prev[id] }));
  const toggleSubsection = (id) => setCollapsedSubsections(prev => ({ ...prev, [id]: !prev[id] }));

  const handleDownloadTxt = () => {
    const lines = [];
    lines.push(`COURSE: ${courseName}`);
    lines.push('Generated by EdCube');
    lines.push('');

    sections.forEach((section, sIdx) => {
      if (section.type === 'break') {
        lines.push(`--- BREAK: ${section.duration} ---`);
        lines.push('');
        return;
      }

      lines.push('='.repeat(60));
      lines.push(`SECTION ${sIdx + 1}: ${section.title}`);
      if (section.description) lines.push(section.description);
      lines.push('');

      (section.subsections || []).forEach((sub, subIdx) => {
        lines.push(`  ${sIdx + 1}.${subIdx + 1} ${sub.title}`);
        if (sub.description) lines.push(`  ${sub.description}`);
        lines.push('');

        (sub.topicBoxes || []).forEach(topic => {
          lines.push(`    TOPIC: ${topic.title}`);
          lines.push(`    Duration: ${topic.duration_minutes || 0} min`);
          if ((topic.pla_pillars || []).length > 0) {
            lines.push(`    PLA Pillars: ${topic.pla_pillars.join(', ')}`);
          }
          if ((topic.learning_objectives || []).length > 0) {
            lines.push('    Learning Objectives:');
            topic.learning_objectives.forEach(obj => lines.push(`      - ${obj}`));
          }

          const videos = videosByTopic[topic.id] || [];
          if (videos.length > 0) {
            lines.push('    Videos:');
            videos.forEach(v => lines.push(`      - ${v.title}: ${v.url}`));
          }

          const allRes = handsOnResources[topic.id] || [];
          const worksheets = allRes.filter(r => r.type === 'worksheet');
          const activities = allRes.filter(r => r.type === 'activity');
          if (worksheets.length > 0) {
            lines.push('    Worksheets:');
            worksheets.forEach(w => lines.push(`      - ${w.title}: ${w.url}`));
          }
          if (activities.length > 0) {
            lines.push('    Activities:');
            activities.forEach(a => lines.push(`      - ${a.title}: ${a.url}`));
          }

          lines.push('');
        });
      });
    });

    const blob = new Blob([lines.join('\n')], { type: 'text/plain;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `${courseName.replace(/[^a-z0-9]/gi, '_')}.txt`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  // ── Colors — matches CourseEditor exactly ─────────────────────────────
  const colors = {
    bg: '#F7F5F0',
    card: '#FFFFFF',
    sectionBorder: '#E7E5E4',
    sectionBg: '#FFFFFF',
    sectionStripe: '#52A67A',       // Green left stripe
    subsectionBg: '#FFFFFF',
    subsectionBorder: '#E7E5E4',
    subsectionStripe: '#5B8FBD',    // Blue left stripe
    topicBg: '#FFFFFF',
    topicBorder: '#E7E5E4',
    topicStripe: '#C2547A',         // Pink/red left stripe
    textPrimary: '#111',
    textSecondary: '#111',
    pillBg: '#F5F5F4',
    pillText: '#333',
    pla: {
      'Personal Growth': '#FEF3C7',
      'Core Learning': '#E0F2FE',
      'Critical Thinking': '#FDF4FF',
      'Application & Impact': '#F0FDF4'
    },
    plaText: {
      'Personal Growth': '#92400E',
      'Core Learning': '#0369A1',
      'Critical Thinking': '#7E22CE',
      'Application & Impact': '#166534'
    }
  };

  // ── Topic Box (read-only) ────────────────────────────────────────────
  const TopicBoxCard = ({ topicBox }) => {
    const [activeTab, setActiveTab] = useState('topic');
    const [hovered, setHovered] = useState(false);

    const videos = videosByTopic[topicBox.id] || [];
    const allResources = handsOnResources[topicBox.id] || [];
    const worksheets = allResources.filter(r => r.type === 'worksheet');
    const activities = allResources.filter(r => r.type === 'activity');

    const tabs = [
      { id: 'topic', label: 'Topic' },
      { id: 'videos', label: videos.length > 0 ? `Videos (${videos.length})` : 'Videos' },
      { id: 'activities', label: activities.length > 0 ? `Activities (${activities.length})` : 'Activities' },
      { id: 'worksheets', label: worksheets.length > 0 ? `Worksheets (${worksheets.length})` : 'Worksheets' },
    ];

    const getYouTubeThumbnail = (url) => {
      try {
        const urlObj = new URL(url);
        let videoId = null;
        if (urlObj.hostname.includes('youtube.com')) {
          videoId = urlObj.searchParams.get('v');
        } else if (urlObj.hostname.includes('youtu.be')) {
          videoId = urlObj.pathname.slice(1).split('?')[0];
        }
        if (videoId) return `https://img.youtube.com/vi/${videoId}/mqdefault.jpg`;
      } catch {}
      return null;
    };

    const renderResourceCards = (resources, type) => {
      if (resources.length === 0) {
        return (
          <div style={{ padding: '14px 16px', color: '#444', fontSize: '14px', fontStyle: 'italic' }}>
            No {type} added for this topic.
          </div>
        );
      }
      return (
        <div style={{
          display: 'flex',
          gap: '10px',
          overflowX: 'auto',
          padding: '12px 16px',
          scrollbarWidth: 'thin',
          scrollbarColor: '#E8E6E1 transparent'
        }}>
          {resources.map((resource, idx) => {
            const thumbnail = type === 'video' ? getYouTubeThumbnail(resource.url) : null;
            const placeholderIcon = type === 'video'
              ? <PlayCircle size={22} style={{ color: '#666' }} />
              : type === 'worksheet'
                ? <FileText size={22} style={{ color: '#666' }} />
                : <Zap size={22} style={{ color: '#666' }} />;
            const placeholderBg = type === 'video' ? '#E8E6E1' : type === 'worksheet' ? '#E4EEE4' : '#E8E4EE';

            return (
              <a
                key={idx}
                href={resource.url}
                target="_blank"
                rel="noopener noreferrer"
                onClick={e => e.stopPropagation()}
                title={resource.title}
                style={{
                  display: 'flex',
                  flexDirection: 'column',
                  width: '130px',
                  flexShrink: 0,
                  border: `1px solid ${colors.topicBorder}`,
                  borderRadius: '8px',
                  overflow: 'hidden',
                  textDecoration: 'none',
                  backgroundColor: '#fff',
                  boxShadow: '0 1px 3px rgba(0,0,0,0.06)',
                  transition: 'box-shadow 0.2s, transform 0.15s'
                }}
                onMouseEnter={e => {
                  e.currentTarget.style.boxShadow = '0 4px 10px rgba(0,0,0,0.14)';
                  e.currentTarget.style.transform = 'translateY(-1px)';
                }}
                onMouseLeave={e => {
                  e.currentTarget.style.boxShadow = '0 1px 3px rgba(0,0,0,0.06)';
                  e.currentTarget.style.transform = 'translateY(0)';
                }}
              >
                {thumbnail ? (
                  <img
                    src={thumbnail}
                    alt={resource.title}
                    style={{ width: '100%', height: '72px', objectFit: 'cover' }}
                  />
                ) : (
                  <div style={{
                    width: '100%',
                    height: '72px',
                    backgroundColor: placeholderBg,
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center'
                  }}>
                    {placeholderIcon}
                  </div>
                )}
                <div style={{ padding: '6px 8px' }}>
                  <p style={{
                    margin: 0,
                    fontSize: '12.1px',
                    fontWeight: '600',
                    color: colors.textPrimary,
                    lineHeight: '1.4',
                    overflow: 'hidden',
                    display: '-webkit-box',
                    WebkitLineClamp: 2,
                    WebkitBoxOrient: 'vertical'
                  }}>
                    {resource.title}
                  </p>
                </div>
              </a>
            );
          })}
        </div>
      );
    };

    return (
      <div
        style={{ marginBottom: '10px' }}
        onMouseEnter={() => setHovered(true)}
        onMouseLeave={() => setHovered(false)}
      >
        <div style={{
          border: `1px solid ${colors.topicBorder}`,
          borderRadius: '10px',
          backgroundColor: colors.topicBg,
          boxShadow: hovered ? '0 4px 12px rgba(0,0,0,0.10)' : '0 1px 3px rgba(0,0,0,0.05)',
          overflow: 'hidden',
          transition: 'box-shadow 0.2s',
          display: 'flex'
        }}>
          {/* Pink/red left stripe */}
          <div style={{ width: '4px', backgroundColor: colors.topicStripe, flexShrink: 0 }} />

          <div style={{ flex: 1, minWidth: 0 }}>
            {/* ── Folder Tab Bar ── */}
            <div style={{
              display: 'flex',
              alignItems: 'center',
              backgroundColor: '#FAFAF9',
              borderBottom: `1px solid ${colors.topicBorder}`,
              paddingLeft: '2px',
              paddingRight: '6px'
            }}>
              {tabs.map(tab => (
                <button
                  key={tab.id}
                  onClick={e => { e.stopPropagation(); setActiveTab(tab.id); }}
                  style={{
                    padding: '8px 11px',
                    border: 'none',
                    borderBottom: activeTab === tab.id ? `2px solid ${colors.topicStripe}` : '2px solid transparent',
                    backgroundColor: 'transparent',
                    cursor: 'pointer',
                    fontSize: '13px',
                    fontWeight: activeTab === tab.id ? '600' : '400',
                    color: activeTab === tab.id ? colors.topicStripe : '#555',
                    transition: 'all 0.15s',
                    whiteSpace: 'nowrap',
                    fontFamily: "'DM Sans', sans-serif"
                  }}
                >
                  {tab.label}
                </button>
              ))}

              <div style={{ flex: 1 }} />

              {/* View details button */}
              <button
                onClick={e => { e.stopPropagation(); setSelectedTopic(topicBox); }}
                style={{
                  padding: '4px 9px',
                  backgroundColor: '#fff',
                  color: '#333',
                  border: `1px solid ${colors.topicBorder}`,
                  borderRadius: '5px',
                  cursor: 'pointer',
                  fontSize: '12.1px',
                  fontWeight: '600',
                  display: 'flex',
                  alignItems: 'center',
                  gap: '4px',
                  flexShrink: 0,
                  fontFamily: "'DM Sans', sans-serif"
                }}
                title="View topic details"
              >
                <Edit2 size={11} /> Details
              </button>
            </div>

            {/* ── Tab Content ── */}
            {activeTab === 'topic' && (
              <div
                onClick={() => setSelectedTopic(topicBox)}
                style={{ padding: '13px 16px', cursor: 'pointer' }}
              >
                <h4 style={{ margin: '0 0 7px', fontSize: '16px', fontWeight: '600', color: '#111' }}>
                  {topicBox.title}
                </h4>

                {(topicBox.learning_objectives || []).length > 0 && (
                  <ul style={{ margin: '0 0 10px', paddingLeft: '18px', fontSize: '14px', color: '#111', lineHeight: '1.6' }}>
                    {topicBox.learning_objectives.slice(0, 3).map((obj, i) => (
                      <li key={i} style={{ marginBottom: '3px' }}>{obj}</li>
                    ))}
                    {topicBox.learning_objectives.length > 3 && (
                      <li style={{ color: '#555', fontStyle: 'italic' }}>
                        +{topicBox.learning_objectives.length - 3} more…
                      </li>
                    )}
                  </ul>
                )}

                <div style={{ display: 'flex', gap: '6px', flexWrap: 'wrap' }}>
                  <span style={{
                    fontSize: '13px', padding: '3px 8px', borderRadius: '4px',
                    backgroundColor: colors.pillBg, color: '#333'
                  }}>
                    🕐 {topicBox.duration_minutes || 0} min
                  </span>
                  {(topicBox.pla_pillars || []).map((pillar, idx) => (
                    <span key={idx} style={{
                      fontSize: '13px', padding: '3px 8px', borderRadius: '4px',
                      backgroundColor: colors.pla[pillar] || colors.pillBg,
                      color: colors.plaText[pillar] || '#333'
                    }}>
                      {pillar}
                    </span>
                  ))}
                </div>
              </div>
            )}

            {activeTab === 'videos' && renderResourceCards(videos, 'video')}
            {activeTab === 'activities' && renderResourceCards(activities, 'activity')}
            {activeTab === 'worksheets' && renderResourceCards(worksheets, 'worksheet')}
          </div>
        </div>
      </div>
    );
  };

  // ── Section (read-only) ──────────────────────────────────────────────
  const SectionView = ({ section, index }) => {
    if (section.type === 'break') {
      return (
        <div style={{
          padding: '12px 16px', marginBottom: '16px',
          backgroundColor: '#FFF9E6', border: `1px solid ${colors.sectionBorder}`,
          borderRadius: '8px', display: 'flex', alignItems: 'center', gap: '8px'
        }}>
          <span style={{ fontWeight: '500', fontSize: '15.4px', color: colors.textPrimary }}>
            ⏸️ Break — {section.duration}
          </span>
        </div>
      );
    }

    const isCollapsed = collapsedSections[section.id];

    return (
      <div style={{
        border: `1px solid ${colors.sectionBorder}`,
        borderRadius: '12px',
        marginBottom: '16px',
        backgroundColor: colors.card,
        overflow: 'hidden',
        boxShadow: '0 1px 3px rgba(0,0,0,0.06)'
      }}>
        {/* Section header */}
        <div style={{
          backgroundColor: colors.sectionBg,
          display: 'flex',
          alignItems: 'center',
          borderBottom: isCollapsed ? 'none' : `1px solid ${colors.sectionBorder}`
        }}>
          {/* Green left stripe */}
          <div style={{
            width: '5px',
            alignSelf: 'stretch',
            backgroundColor: colors.sectionStripe,
            flexShrink: 0
          }} />

          <div style={{ flex: 1, padding: '12px 14px', display: 'flex', alignItems: 'center', gap: '10px' }}>
            <button
              onClick={() => toggleSection(section.id)}
              style={{
                background: 'none', border: 'none', cursor: 'pointer',
                fontSize: '12.1px', color: colors.sectionStripe, padding: 0, flexShrink: 0,
                transition: 'transform 0.2s',
                transform: isCollapsed ? 'rotate(0deg)' : 'rotate(90deg)'
              }}
            >
              ▶
            </button>

            <span style={{
              fontSize: '11px', fontWeight: '700', textTransform: 'uppercase',
              letterSpacing: '0.7px', color: colors.sectionStripe,
              background: '#DCFCE7', padding: '2px 7px', borderRadius: '4px', flexShrink: 0
            }}>
              Section {index + 1}
            </span>

            <span style={{
              fontSize: '18px', fontWeight: '600', color: '#111',
              flex: 1, letterSpacing: '-0.2px'
            }}>
              {section.title}
            </span>
          </div>
        </div>

        {/* Section description */}
        {!isCollapsed && section.description && (
          <div style={{
            backgroundColor: '#FAFAF9',
            padding: '9px 16px 9px 21px',
            borderBottom: `1px solid ${colors.sectionBorder}`
          }}>
            <span style={{ fontSize: '14px', color: '#333' }}>
              {section.description}
            </span>
          </div>
        )}

        {/* Subsections */}
        {!isCollapsed && (
          <div style={{ padding: '14px 16px' }}>
            {(section.subsections || []).length === 0 ? (
              <div style={{
                textAlign: 'center', padding: '24px 20px',
                border: '1px dashed #e5e7eb', borderRadius: '8px',
                backgroundColor: '#fafafa', color: '#444', fontSize: '14px'
              }}>
                No subsections in this section
              </div>
            ) : (
              (section.subsections || []).map((sub, subIdx) => {
                const isSubCollapsed = collapsedSubsections[sub.id];

                // Aggregate unique PLA pillars from this subsection's topic boxes
                const subPillarSet = new Set();
                (sub.topicBoxes || []).forEach(t => (t.pla_pillars || []).forEach(p => subPillarSet.add(p)));
                const subPillars = Array.from(subPillarSet).slice(0, 2);

                return (
                  <div key={sub.id} style={{ marginBottom: '10px' }}>
                    <div style={{
                      border: `1px solid ${colors.subsectionBorder}`,
                      borderRadius: '10px',
                      backgroundColor: colors.subsectionBg,
                      overflow: 'hidden'
                    }}>
                      {/* Subsection header */}
                      <div style={{
                        display: 'flex',
                        alignItems: 'center',
                        borderBottom: isSubCollapsed ? 'none' : `1px solid ${colors.subsectionBorder}`
                      }}>
                        {/* Blue left stripe */}
                        <div style={{
                          width: '4px', alignSelf: 'stretch',
                          backgroundColor: colors.subsectionStripe, flexShrink: 0
                        }} />

                        <div
                          style={{ flex: 1, padding: '9px 12px', display: 'flex', alignItems: 'center', gap: '8px', cursor: 'pointer' }}
                          onClick={() => toggleSubsection(sub.id)}
                        >
                          <button style={{
                            background: 'none', border: 'none', cursor: 'pointer',
                            fontSize: '11px', color: colors.subsectionStripe, padding: 0, flexShrink: 0,
                            transition: 'transform 0.2s',
                            transform: isSubCollapsed ? 'rotate(0deg)' : 'rotate(90deg)'
                          }}>
                            ▶
                          </button>

                          <span style={{
                            fontSize: '11px', fontWeight: '700', textTransform: 'uppercase',
                            letterSpacing: '0.6px', color: colors.subsectionStripe, flexShrink: 0
                          }}>
                            {index + 1}.{subIdx + 1}
                          </span>

                          <span style={{
                            fontSize: '15px', fontWeight: '600', color: '#111', flex: 1
                          }}>
                            {sub.title}
                          </span>

                          {/* PLA pillar tags from sub's topics */}
                          {subPillars.map(pillar => (
                            <span key={pillar} style={{
                              fontSize: '11px', fontWeight: '500', flexShrink: 0,
                              padding: '2px 7px', borderRadius: '4px',
                              backgroundColor: colors.pla[pillar] || colors.pillBg,
                              color: colors.plaText[pillar] || colors.textSecondary
                            }}>
                              {pillar}
                            </span>
                          ))}
                        </div>
                      </div>

                      {/* Subsection description */}
                      {!isSubCollapsed && sub.description && (
                        <div style={{
                          backgroundColor: '#FAFAF9',
                          padding: '7px 12px 10px 16px',
                          borderBottom: `1px solid ${colors.subsectionBorder}`
                        }}>
                          <span style={{ fontSize: '14px', color: '#333' }}>
                            {sub.description}
                          </span>
                        </div>
                      )}

                      {/* Topic boxes */}
                      {!isSubCollapsed && (
                        <div style={{ padding: '12px' }}>
                          {(sub.topicBoxes || []).length === 0 ? (
                            <div style={{
                              textAlign: 'center', padding: '24px 20px',
                              border: '1px dashed #e5e7eb', borderRadius: '8px',
                              backgroundColor: '#fafafa',
                              color: colors.textSecondary, fontSize: '14.3px'
                            }}>
                              No topic boxes in this subsection
                            </div>
                          ) : (
                            (sub.topicBoxes || []).map(topic => (
                              <TopicBoxCard key={topic.id} topicBox={topic} />
                            ))
                          )}
                        </div>
                      )}
                    </div>
                  </div>
                );
              })
            )}
          </div>
        )}
      </div>
    );
  };

  // ── Stats ────────────────────────────────────────────────────────────
  const sectionCount = sections.filter(s => s.type !== 'break').length;
  const subsectionCount = sections.reduce((acc, s) => acc + (s.subsections?.length || 0), 0);
  const topicCount = sections.reduce((acc, s) =>
    acc + (s.subsections?.reduce((t, sub) => t + (sub.topicBoxes?.length || 0), 0) || 0), 0
  );

  // ── Render ───────────────────────────────────────────────────────────
  return (
    <>
      {/* Top Bar */}
      <div style={{
        padding: '12px 28px', borderBottom: `1px solid ${colors.sectionBorder}`,
        display: 'flex', justifyContent: 'space-between', alignItems: 'center',
        backgroundColor: 'white', boxShadow: '0 1px 3px rgba(0,0,0,0.06)'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '12px', flexWrap: 'wrap' }}>
          <h2 style={{ margin: 0, fontSize: '22px', color: colors.textPrimary }}>EdCube</h2>
          <span style={{ fontSize: '18.7px', fontWeight: '600', color: colors.textPrimary }}>
            {courseName}
          </span>
          <span style={{
            fontSize: '12.1px',
            color: isOwner ? '#1d4ed8' : '#059669',
            backgroundColor: isOwner ? '#EFF6FF' : '#ECFDF5',
            padding: '3px 8px', borderRadius: '10px', fontWeight: '600'
          }}>
            {isOwner ? 'View Mode' : 'View Only'}
          </span>
          {ownerName && (
            <span style={{
              fontSize: '13px', color: '#333', backgroundColor: '#f3f4f6',
              padding: '4px 10px', borderRadius: '12px', fontWeight: '500'
            }}>
              By {ownerName}
            </span>
          )}
        </div>

        <div style={{ display: 'flex', gap: '10px', alignItems: 'center' }}>
          {isOwner && (
            <button
              onClick={handleDownloadTxt}
              style={{
                display: 'flex', alignItems: 'center', gap: '6px',
                padding: '7px 14px',
                backgroundColor: '#fff',
                color: '#111',
                border: '1px solid #d1d5db', borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '14.3px', fontWeight: '500',
                transition: 'background-color 0.15s ease'
              }}
              onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = '#f9fafb'; }}
              onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = '#fff'; }}
              title="Download course as TXT"
            >
              <Download size={14} />
              Download
            </button>
          )}
          {isOwner && onEditInWorkspace && (
            <button
              onClick={onEditInWorkspace}
              style={{
                display: 'flex', alignItems: 'center', gap: '6px',
                padding: '7px 16px',
                backgroundColor: '#1d4ed8',
                color: 'white',
                border: 'none', borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '14.3px', fontWeight: '600',
                transition: 'background-color 0.15s ease'
              }}
              onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = '#1e40af'; }}
              onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = '#1d4ed8'; }}
            >
              <PencilLine size={14} />
              Edit in Course Workspace
            </button>
          )}
          {isCollaborator && onEditAsCollaborator && (
            <button
              onClick={onEditAsCollaborator}
              style={{
                display: 'flex', alignItems: 'center', gap: '6px',
                padding: '7px 16px',
                backgroundColor: '#059669',
                color: 'white',
                border: 'none', borderRadius: '6px',
                cursor: 'pointer',
                fontSize: '14.3px', fontWeight: '600',
                transition: 'background-color 0.15s ease'
              }}
              onMouseEnter={(e) => { e.currentTarget.style.backgroundColor = '#047857'; }}
              onMouseLeave={(e) => { e.currentTarget.style.backgroundColor = '#059669'; }}
            >
              <PencilLine size={14} />
              Edit as Collaborator
            </button>
          )}
          <button
            onClick={() => navigate(-1)}
            style={{
              display: 'flex', alignItems: 'center', gap: '6px',
              padding: '7px 14px', backgroundColor: '#6b7280', color: 'white',
              border: 'none', borderRadius: '6px', cursor: 'pointer', fontSize: '14.3px'
            }}
          >
            <ArrowLeft size={14} /> Back
          </button>
        </div>
      </div>

      {/* Stats bar */}
      <div style={{
        padding: '10px 28px', backgroundColor: 'white',
        borderBottom: `1px solid ${colors.sectionBorder}`,
        display: 'flex', gap: '10px', alignItems: 'center', justifyContent: 'center'
      }}>
        <span style={{ fontSize: '14px', color: '#444' }}>
          {sectionCount} section{sectionCount !== 1 ? 's' : ''} {'\u2022'}{' '}
          {subsectionCount} subsection{subsectionCount !== 1 ? 's' : ''} {'\u2022'}{' '}
          {topicCount} topic box{topicCount !== 1 ? 'es' : ''}
        </span>
      </div>

      {/* Main content */}
      <div style={{ flex: 1, overflowY: 'auto', padding: '24px 28px', backgroundColor: colors.bg }}>
        {sections.length === 0 ? (
          <div style={{
            textAlign: 'center', padding: '80px 20px',
            border: `1px solid ${colors.sectionBorder}`, borderRadius: '16px',
            backgroundColor: 'white'
          }}>
            <p style={{ fontSize: '17.6px', color: colors.textPrimary, fontWeight: '600', margin: '0 0 4px' }}>
              This course has no sections yet
            </p>
          </div>
        ) : (
          sections.map((section, idx) => (
            <SectionView key={section.id} section={section} index={idx} />
          ))
        )}
      </div>

      {/* Topic detail modal (view-only) */}
      {selectedTopic && (
        <TopicDetailsModal
          topic={selectedTopic}
          onClose={() => setSelectedTopic(null)}
          readOnly
        />
      )}
    </>
  );
};

export default CourseViewer;
